const WORDS_DATABASE = [
  // المفردات الأساسية
  { ar: 'كتاب', en: 'BOOK', pronunciation: 'بوك' },
  { ar: 'قلم', en: 'PEN', pronunciation: 'بين' },
  { ar: 'تفاحة', en: 'APPLE', pronunciation: 'أبل' },
  { ar: 'سيارة', en: 'CAR', pronunciation: 'كار' },
  { ar: 'مدرسة', en: 'SCHOOL', pronunciation: 'سكول' },
  { ar: 'شمس', en: 'SUN', pronunciation: 'سان' },
  { ar: 'قمر', en: 'MOON', pronunciation: 'مون' },
  { ar: 'ماء', en: 'WATER', pronunciation: 'ووتر' },
  { ar: 'بيت', en: 'HOUSE', pronunciation: 'هاوس' },
  { ar: 'صديق', en: 'FRIEND', pronunciation: 'فريند' },
  { ar: 'طعام', en: 'FOOD', pronunciation: 'فود' },
  { ar: 'وقت', en: 'TIME', pronunciation: 'تايم' },
  { ar: 'عمل', en: 'WORK', pronunciation: 'ويرك' },
  { ar: 'هاتف', en: 'PHONE', pronunciation: 'فون' },
  { ar: 'باب', en: 'DOOR', pronunciation: 'دور' },
  { ar: 'نافذة', en: 'WINDOW', pronunciation: 'ويندو' },
  { ar: 'مال', en: 'MONEY', pronunciation: 'ماني' },
  { ar: 'عائلة', en: 'FAMILY', pronunciation: 'فاميلي' },
  { ar: 'مدينة', en: 'CITY', pronunciation: 'سيتي' },
  { ar: 'طريق', en: 'ROAD', pronunciation: 'رود' },

  // الجمل والعبارات اليومية
  { ar: 'صباح الخير', en: 'GOOD MORNING', pronunciation: 'غود مورنينغ' },
  { ar: 'مساء الخير', en: 'GOOD EVENING', pronunciation: 'غود إيفنينغ' },
  { ar: 'شكراً لك', en: 'THANK YOU', pronunciation: 'ثانك يو' },
  { ar: 'كيف حالك؟', en: 'HOW ARE YOU?', pronunciation: 'هاو أر يو؟' },
  { ar: 'أنا أحبك', en: 'I LOVE YOU', pronunciation: 'آي لاف يو' },
  { ar: 'أراك لاحقاً', en: 'SEE YOU LATER', pronunciation: 'سي يو ليتر' },
  { ar: 'مع السلامة', en: 'GOODBYE', pronunciation: 'غود باي' },
  { ar: 'أنا جائع', en: 'I AM HUNGRY', pronunciation: 'آي أيم هانغري' },
  { ar: 'أنا تعبان', en: 'I AM TIRED', pronunciation: 'آي أيم تايرد' },
  { ar: 'ما اسمك؟', en: 'WHAT IS YOUR NAME?', pronunciation: 'وات إز يور نيم؟' },
  { ar: 'سررت بلقائك', en: 'NICE TO MEET YOU', pronunciation: 'نايس تو ميت يو' },
  { ar: 'من فضلك', en: 'PLEASE', pronunciation: 'بليز' },
  { ar: 'أنا لا أفهم', en: 'I DO NOT UNDERSTAND', pronunciation: 'آي دو نوت أندرستاند' },
  { ar: 'ساعدني', en: 'HELP ME', pronunciation: 'هيلب مي' },
  { ar: 'كم السعر؟', en: 'HOW MUCH IS IT?', pronunciation: 'هاو ماتش إز إت؟' },
];

